plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.blijchislo'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.blijchislo'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0'

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
}


dependencies {
    testImplementation 'junit:junit:4.13.2'
}
